# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [66]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [67]:
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv'
baby_names = pd.read_csv(url, sep=',')

### Step 4. See the first 10 entries

In [68]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [69]:
## del baby_names['Unnamed: 0']  ##del 함수는 하나씩 삭제 가능
## del baby_names['Id']
baby_names.drop(['Unnamed: 0','Id'], axis=1)  ##두 개 이상 삭제 시 drop 사용

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

### Step 6. Is there more male or female names in the dataset?

In [70]:
gender_counts = baby_names['Gender'].value_counts()
if gender_counts['M']>gender_counts['F']:
  print("Male are more")
else:
   print("Female are more")

Female are more

In [64]:
## 답지
baby_names['Gender'].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 7. Group the dataset by name and assign to names
## column 'Name' 으로 group --> names로 할당

In [79]:
baby_names.drop(['Unnamed: 0','Id','Gender','State'],axis=1)
names = baby_names.groupby('Name').sum()
names.head()
print(names.shape)
names.sort_values("Count", ascending=0).head()

## 왜 답지랑 똑같이 안나올까....핳하ㅓㅎ

(17632, 6)

,Unnamed: 0,Id,Year,Gender,State,Count
Name,,,,,,
Jacob,1665680788,1665681356,1141099,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,242874
Emma,1629481684,1629482250,1137085,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,214852
Michael,1687520717,1687521295,1161152,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMFF...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,214405
Ethan,1660807908,1660808475,1139091,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,209277
Isabella,1630131220,1630131786,1137090,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF...,AKAKAKAKAKAKAKAKAKAKAKALALALALALALALALALALALAR...,204798

### Step 8. How many different names exist in the dataset?
## How many different --> nunique 함수 사용

In [42]:
names.nunique()

         Unnamed: 0   Id  Year  Gender  State  Count
Name
Aaban             2    2     2       1      1      1
Aadan             4    4     3       1      2      3
Aadarsh           1    1     1       1      1      1
Aaden           196  196     9       1     45     43
Aadhav            1    1     1       1      1      1
...             ...  ...   ...     ...    ...    ...
Zyra              7    7     5       1      3      4
Zyrah             2    2     2       1      2      2
Zyren             1    1     1       1      1      1
Zyria            10   10     7       1      3      3
Zyriah            9    9     8       1      3      5

[17632 rows x 6 columns]

In [80]:
## 답지
len(names)

17632

### Step 9. What is the name with most occurrences?

In [53]:
## names.value_counts().idxmax() 이렇게 했을때 오류떴음. GPT는 groupby 하고 바로 valuecounts 못쓴다고 함.
## 오류의 원인은 names에 groupby()로 그룹화된 객체가 할당되어 있기 때문입니다. groupby()는 그룹화된 객체를 생성하지만, 바로 value_counts() 같은 함수는 사용할 수 없습니다.
## groupby() 객체에는 바로 사용할 수 있는 value_counts()가 없기 때문에 이 오류가 발생한 것입니다.
## --> GPT는 해결방법으로 size 함수를 알려주었으나, 이해가 잘 안가서 baby_names 로 찾음
baby_names['Name'].value_counts().idxmax()

'Riley'

In [81]:
## 답지
names.Count.idxmax() ##group화된 객체에는 valuecounts가 아니고 Count 함수써야하는 듯

'Jacob'

### Step 10. How many different names have the least occurrences?

In [62]:
names.size().min()

1

In [82]:
## names.Count.min() --> 이거 아님

5

In [86]:
## 답지
len(names[names.Count == names.Count.min()])

2578

### Step 11. What is the median name occurrence?

In [88]:
names[names.Count == names.Count.median()]

         Unnamed: 0        Id   Year    Gender             State  Count
Name
Aishani     7810519   7810526  14078   FFFFFFF    CACACACACAILNJ     49
Alara      18841019  18841027  16079  FFFFFFFF  CACACAFLNYNYNYTX     49
Alysse     22629397  22629405  16057  FFFFFFFF  CACACAMINYTXTXTX     49
Ameir      21780403  21780411  16086  MMMMMMMM  CAMIMIMIMIMINYOH     49
Anely       4349533   4349541  16071  FFFFFFFF  CACACACACACACACA     49
...             ...       ...    ...       ...               ...    ...
Sriram      9208196   9208203  14054   MMMMMMM    CACACACACACATX     49
Trinton    32822294  32822302  16069  MMMMMMMM  FLLAOKTXTXTXTXTX     49
Vita       10241625  10241632  14075   FFFFFFF    CACACACACANYNY     49
Yoni        6439146   6439154  16060  MMMMMMMM  CACACACACACAFLFL     49
Zuleima     3521366   3521373  14050   FFFFFFF    AZCACACACACACA     49

[66 rows x 6 columns]

### Step 12. What is the standard deviation of names?

In [89]:
names.Count.std()

11006.06946789057

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [90]:
names.describe()
## Unnamed, Id, Year 열이 왜 계속 살아있는지 모르겠스빈다영...

         Unnamed: 0            Id          Year          Count
count  1.763200e+04  1.763200e+04  1.763200e+04   17632.000000
mean   1.631922e+08  1.631922e+08  1.158117e+05    2008.932169
std    3.504512e+08  3.504513e+08  2.451618e+05   11006.069468
min    8.606400e+04  8.606500e+04  2.004000e+03       5.000000
25%    4.918374e+06  4.918375e+06  4.017000e+03      11.000000
50%    1.963462e+07  1.963463e+07  1.606100e+04      49.000000
75%    1.071826e+08  1.071826e+08  7.846425e+04     337.000000
max    3.223035e+09  3.223036e+09  2.233993e+06  242874.000000